CREATE DATABASE db_generation_game_online;

USE db_generation_game_online;

CREATE TABLE tb_classes(ID BIGINT(5) AUTO_INCREMENT,
CLASSES VARCHAR(255) NOT NULL,
PRIMARY KEY(ID));

CREATE TABLE tb_personagens(ID BIGINT(8) AUTO_INCREMENT,
PERSONAGEM VARCHAR(255),
ATAQUE INT,
DEFESA INT,
ORIGEM VARCHAR(255),
CATEGORIA_ID BIGINT,
PRIMARY KEY(ID),
FOREIGN KEY(CATEGORIA_ID) REFERENCES tb_classes(ID));

INSERT INTO tb_classes (CLASSES) VALUES ("GUERREIRO(A)");
INSERT INTO tb_classes (CLASSES) VALUES ("MAGO(A)");
INSERT INTO tb_classes (CLASSES) VALUES ("NINJA");
INSERT INTO tb_classes (CLASSES) VALUES ("CURANDEIRO(A)");
INSERT INTO tb_classes (CLASSES) VALUES ("ARQUEIRO(A)");

SELECT * FROM tb_classes;

INSERT INTO tb_personagens (PERSONAGEM,ATAQUE,DEFESA,ORIGEM,CATEGORIA_ID)
VALUES ("ORION",700,2000,"GRECIA",1);
INSERT INTO tb_personagens (PERSONAGEM,ATAQUE,DEFESA,ORIGEM,CATEGORIA_ID)
VALUES ("CASSANDRA",2000,650,"ESPANHA",2);
INSERT INTO tb_personagens (PERSONAGEM,ATAQUE,DEFESA,ORIGEM,CATEGORIA_ID)
VALUES ("KILLER",1800,850,"DESCONHECIDO",3);
INSERT INTO tb_personagens (PERSONAGEM,ATAQUE,DEFESA,ORIGEM,CATEGORIA_ID)
VALUES ("ESTRELA",620,2000,"BRASIL",4);
INSERT INTO tb_personagens (PERSONAGEM,ATAQUE,DEFESA,ORIGEM,CATEGORIA_ID)
VALUES ("AKEMI",1900,700,"JAPÃO",5);
INSERT INTO tb_personagens (PERSONAGEM,ATAQUE,DEFESA,ORIGEM,CATEGORIA_ID)
VALUES ("DRACO",2200,700,"ITALIA",2);
INSERT INTO tb_personagens (PERSONAGEM,ATAQUE,DEFESA,ORIGEM,CATEGORIA_ID)
VALUES ("HEISENBERG",750,1800,"EUA",4);
INSERT INTO tb_personagens (PERSONAGEM,ATAQUE,DEFESA,ORIGEM,CATEGORIA_ID)
VALUES ("PANDORA",650,2000,"CANADA",1);

SELECT * FROM tb_personagens;

SELECT * FROM tb_personagens WHERE ATAQUE > 2000;
SELECT * FROM tb_personagens WHERE DEFESA >= 1000 AND DEFESA <= 2000;

SELECT * FROM tb_personagens WHERE PERSONAGEM LIKE "%C%";

SELECT * FROM tb_classes INNER JOIN tb_personagens ON
tb_personagens.CATEGORIA_ID = tb_classes.ID;

SELECT * FROM tb_classes INNER JOIN tb_personagens ON 
tb_personagens.CATEGORIA_ID = tb_classes.ID WHERE CATEGORIA_ID = 1;