CREATE DATABASE DB_DEVAS_RH;

USE DB_DEVAS_RH;

CREATE TABLE TB_COLABORADORES(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(1000),
IDADE INT,
TELEFONE INT,
CARGO CHAR(255),
SALARIO INT,
PRIMARY KEY(ID)
);

INSERT INTO TB_COLABORADORES (NOME,IDADE,TELEFONE,CARGO,SALARIO) 
VALUES("Amanda",28,988324455,"Recepcionista",1500);
INSERT INTO TB_COLABORADORES (NOME,IDADE,TELEFONE,CARGO,SALARIO) 
VALUES("Roberto",20,944167623,"Auxiliar Administrativo",1800);
INSERT INTO TB_COLABORADORES (NOME,IDADE,TELEFONE,CARGO,SALARIO) 
VALUES("Leandro",34,974526891,"Gestor de Marketing",3200);
INSERT INTO TB_COLABORADORES (NOME,IDADE,TELEFONE,CARGO,SALARIO) 
VALUES("Helena",22,994305241,"Deva Jr",3500);
INSERT INTO TB_COLABORADORES (NOME,IDADE,TELEFONE,CARGO,SALARIO) 
VALUES("Rose",48,962439712,"Analista de RH",2800);

SELECT * FROM TB_COLABORADORES WHERE SALARIO > 2000;
SELECT * FROM TB_COLABORADORES WHERE SALARIO < 2000;

UPDATE TB_COLABORADORES SET IDADE = 25 WHERE ID = 4;
UPDATE TB_COLABORADORES SET TELEFONE = 970248091 WHERE ID = 1;

SELECT * FROM TB_COLABORADORES;