CREATE DATABASE db_curso_da_minha_vida;

USE db_curso_da_minha_vida;

CREATE TABLE tb_cursos(ID BIGINT(5) AUTO_INCREMENT,
PRODUTOS VARCHAR(255) NOT NULL,
PRIMARY KEY(ID));

CREATE TABLE tb_categorias(ID BIGINT(8) AUTO_INCREMENT,
NOME VARCHAR(255),
PRECO DECIMAL (6,2),
PROFESSOR VARCHAR(255) NOT NULL,
TIPO_AULA VARCHAR(255),
CATEGORIA_ID BIGINT,
PRIMARY KEY(ID),
FOREIGN KEY(CATEGORIA_ID) REFERENCES tb_cursos(ID));

INSERT INTO tb_cursos (PRODUTOS) VALUES ("DESENHO E PINTURA");
INSERT INTO tb_cursos (PRODUTOS) VALUES ("PROGRAMACAO");
INSERT INTO tb_cursos (PRODUTOS) VALUES ("IDIOMAS");
INSERT INTO tb_cursos (PRODUTOS) VALUES ("CULINARIA");
INSERT INTO tb_cursos (PRODUTOS) VALUES ("CROCHE");

SELECT * FROM tb_cursos;

INSERT INTO tb_categorias (NOME,PRECO,PROFESSOR,TIPO_AULA,CATEGORIA_ID)
VALUES ("CURSO DE JAVASCRIPT",599.9,"ANNA FERNANDES","ONLINE",2);
INSERT INTO tb_categorias (NOME,PRECO,PROFESSOR,TIPO_AULA,CATEGORIA_ID)
VALUES ("CURSO DE FRANCES",799.9,"CASTIEL ALBUQUERQUE","ONLINE E PRESENCIAL",3);
INSERT INTO tb_categorias (NOME,PRECO,PROFESSOR,TIPO_AULA,CATEGORIA_ID)
VALUES ("CURSO DE CULINARIA MINEIRA",229.9,"EDILSON QUEIROZ","PRESENCIAL",4);
INSERT INTO tb_categorias (NOME,PRECO,PROFESSOR,TIPO_AULA,CATEGORIA_ID)
VALUES ("CURSO DE CROCHE BASICO",229.9,"ELIETE DRUMMOND","PRESENCIAL E ONLINE",5);
INSERT INTO tb_categorias (NOME,PRECO,PROFESSOR,TIPO_AULA,CATEGORIA_ID)
VALUES ("CURSO DE DESENHO PARA INICIANTES",359.9,"AMANDA SILVEIRA","ONLINE E PRESENCIAL",1);
INSERT INTO tb_categorias (NOME,PRECO,PROFESSOR,TIPO_AULA,CATEGORIA_ID)
VALUES ("APRENDA COREANO EM 2 ANOS",999.9,"MINJI PARK","PRESENCIAL",3);
INSERT INTO tb_categorias (NOME,PRECO,PROFESSOR,TIPO_AULA,CATEGORIA_ID)
VALUES ("APRENDA C# EM 3 MESES",789.9,"MICHELE DUARTE","ONLINE",2);
INSERT INTO tb_categorias (NOME,PRECO,PROFESSOR,TIPO_AULA,CATEGORIA_ID)
VALUES ("CURSO DE CULINARIA ITALIANA",459.9,"FRANCESCO BIANCHI","PRESENCIAL",4);

SELECT * FROM tb_categorias;

SELECT * FROM tb_categorias WHERE PRECO > 500;
SELECT * FROM tb_categorias WHERE PRECO >= 600 AND PRECO <= 1000;

SELECT * FROM tb_categorias WHERE NOME LIKE "%J%";

SELECT * FROM tb_cursos INNER JOIN tb_categorias ON
tb_categorias.CATEGORIA_ID = tb_cursos.ID;

SELECT * FROM tb_cursos INNER JOIN tb_categorias ON 
tb_categorias.CATEGORIA_ID = tb_cursos.ID WHERE CATEGORIA_ID = 4;