CREATE DATABASE DB_ESCOLA;

USE DB_ESCOLA;

CREATE TABLE TB_ALUNOS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(1000),
RA INT,
SERIE CHAR(255),
PERIODO CHAR(255),
NOTA INT,
PRIMARY KEY(ID)
);

INSERT INTO TB_ALUNOS(NOME,RA,SERIE,PERIODO,NOTA)
VALUES("AMANDA",547852,"6F","TARDE",8);
INSERT INTO TB_ALUNOS(NOME,RA,SERIE,PERIODO,NOTA)
VALUES("ADONIS",134584,"3A","MANHA",6);
INSERT INTO TB_ALUNOS(NOME,RA,SERIE,PERIODO,NOTA)
VALUES("FERNANDA",713692,"1C","MANHA",10);
INSERT INTO TB_ALUNOS(NOME,RA,SERIE,PERIODO,NOTA)
VALUES("GABRIEL",405890,"8E","NOITE",9);
INSERT INTO TB_ALUNOS(NOME,RA,SERIE,PERIODO,NOTA)
VALUES("HELENA",305068,"8B","TARDE",7);
INSERT INTO TB_ALUNOS(NOME,RA,SERIE,PERIODO,NOTA)
VALUES("NATHALIE",924036,"8A","NOITE",10);
INSERT INTO TB_ALUNOS(NOME,RA,SERIE,PERIODO,NOTA)
VALUES("OTAVIO",221784,"2E","MANHA",4);
INSERT INTO TB_ALUNOS(NOME,RA,SERIE,PERIODO,NOTA)
VALUES("PAOLA",601780,"4F","TARDE",3);

SELECT * FROM TB_ALUNOS WHERE NOTA > 7;
SELECT * FROM TB_ALUNOS WHERE NOTA < 7;

UPDATE TB_ALUNOS SET NOTA=5 WHERE ID=8;
UPDATE TB_ALUNOS SET SERIE="8E", PERIODO="NOITE" WHERE ID=5;

SELECT * FROM TB_ALUNOS;